#this config is based on the newest update after the 0.8.4 i suppose the version was 
wallpaper {
    monitor = eDP-1
    path = /path/to/powerBW.jpg
  # also the background is designed for my screen display size 1366x768
    fit_mode = cover
}
